#' @description
#' Constructor of the class scRNAseq (might be extended in the future).
#'
#' @rdname constructors
#' @name constructors
#' @title constructors
NULL

#' singlecellRNAseq
#'
#' @usage
#' singlecellRNAseq(experimentName, countMatrix, species, outputDirectory, 
#' tSNElist=list(new("Tsne")))
#'
#' @param experimentName character string representing the name of the
#' experiment. Many output of scRNAseq will use this name.
#' @param countMatrix An integer matrix representing the raw count matrix with
#' reads or unique molecular identifiers (UMIs).
#' @param species character string representing the species of interest.
#' Currently limited to "mouse" and "human".
#' @param outputDirectory A character string of the path to the root output
#' folder.
#' @param tSNEList List of 'Tsne' objects representing the different tSNE
#' coordinates generated by CONCLUS.
#' 
#' @return Object of class scRNAseq
#'
#' @rdname constructors
#' 
#' @examples
#' experimentName <- "Bergiers"
#' countMatrix <- as.matrix(read.delim(system.file(
#' "extdata/test_countMatrix.tsv", package="conclus")))
#' outputDirectory <- "YourOutputDirectory"
#' columnsMetaData <- read.delim(
#' system.file("extdata/Bergiers_colData_filtered.tsv", package="conclus"))
#'
#' ## Create the initial object
#' scr <- singlecellRNAseq(experimentName = experimentName,
#'                 countMatrix     = countMatrix,
#'                 species         = "mouse",
#'                 outputDirectory = outputDirectory)
#'                 
#' @aliases singlecellRNAseq
#' @seealso scRNAseq-class
#' @export singlecellRNAseq
singlecellRNAseq <- function(experimentName, countMatrix, species,
        outputDirectory, tSNElist=list(new("Tsne"))){

    new("scRNAseq",
            experimentName=experimentName,
            countMatrix=countMatrix,
            species=species,
            outputDirectory=outputDirectory,
            tSNEList=tSNElist)
}










#' TsneCluster
#'
#' @usage
#' TsneCluster(name, pc, perplexity, coordinates)
#'
#' @param name A 'character' string representing the name of the tSNE 
#' coordinates.
#' @param pc A 'numeric' value representing the number of principal components
#' used by CONCLUS to perfom a PCA before calculating the tSNE.
#' @param perplexity  A 'numeric'. Default: c(30, 40)
#' @param coordinates A 'numeric' matrix that contains the coordinates
#' of one tSNE solution.
#' 
#' @return Object of class Tsne
#'
#' @rdname constructors
#' 
#' @examples
#'
#' mat <- matrix(seq_len(20), ncol=2)
#' colnames(mat) <- c("X", "Y")
#' TsneCluster(name = "test", pc = 30, perplexity = 4, 
#' coordinates = mat)
#'                                              
#' @aliases TsneCluster
#' @seealso Tsne-class
#' @export TsneCluster
TsneCluster <- function(name, pc, perplexity, coordinates){
    
    new("Tsne",
            name=name,
            pc=pc,
            perplexity=perplexity,
            coordinates=coordinates)
}

